name: Publish Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.7]

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - uses: Gr1N/setup-poetry@v2
      - run: |
          ls
          poetry run pip install --upgrade pip
          poetry install
          poetry publish --build
